version: '3.9'

services:
  rest-api:
    container_name: academic-events
    restart: unless-stopped
    build:
      context: ./
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
