version: '3.9'

services:
  academiceventsapi:
    image: academiceventsapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
